stages:
  - testing

.install_dependencies: &install
  - python --version
  - echo -e "\e[0Ksection_start:`date +%s`:dependencies[collapsed=true]\r\e[0KInstalling Python dependencies..."
  - python -m venv venv
  - source venv/bin/activate
  - pip install uv
  # Use `uv` to install the local package
  - uv sync
  - uv build
  - uv add --dev pytest coverage
  - echo -e "\e[0Ksection_end:`date +%s`:dependencies\r\e[0K"

# ************************ testing ************************
pytest:
  stage: testing
  tags:
    - docker
  image: python:${PY_VERSION}
  before_script:
    - *install
  script:
    - cd test
    - python -m pytest --junitxml=pytest_$PY_VERSION.xml --cov=RWTHPlots
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  needs: [ ]
  artifacts:
    when: always
    reports:
      junit: test/pytest_$PY_VERSION.xml
    paths:
      - test/pytest_$PY_VERSION.xml
  parallel:
    matrix:
      - PY_VERSION: [ "3.9", "3.10", "3.11" ]
