[project]
name = "rwthplots"
version = "3.2.0"
description = "Adding standard themes with RWTH Aachen University colours to matplotlib"
readme = "README.md"
authors = [
  { name = "Steffen Kortmann", email = "s.kortmann@iaew.rwth-aachen.de" },
  { name = "Florian Schmidtke", email = "f.schmidtke@iaew.rwth-aachen.de" },
]
requires-python = ">=3.10"
license = {text = "MIT"}
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Scientific/Engineering :: Visualization",
]
dependencies = [
  "matplotlib>=3.7",
  "numpy>=1.21",
]

[project.urls]
Homepage = "https://github.com/RWTH-IAEW/rwthplots"
Repository = "https://github.com/RWTH-IAEW/rwthplots"
Issues = "https://github.com/RWTH-IAEW/rwthplots/issues"
Changelog = "https://github.com/RWTH-IAEW/rwthplots/blob/main/CHANGELOG.md"

[project.optional-dependencies]
examples = ["rwth-cd-colors>=0.1.1"]

[dependency-groups]
dev = [
  "coverage>=7.8.2",
  "mkdocs>=1.6.1",
  "mkdocs-material>=9.7.6",
  "mkdocstrings>=1.0.4",
  "mkdocstrings-python>=2.0.3",
  "pytest>=8.4.0",
  "pytest-cov>=6.1.1",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["rwthplots*"]

[tool.setuptools.package-dir]
"" = "src"

[project.entry-points."matplotlib.style"]
"rwthplots.styles"          = "rwthplots.styles"
"rwthplots.styles.color"    = "rwthplots.styles.color"
"rwthplots.styles.misc"     = "rwthplots.styles.misc"
"rwthplots.styles.journals" = "rwthplots.styles.journals"
"rwthplots.styles.size"     = "rwthplots.styles.size"

[tool.setuptools.package-data]
rwthplots = [
    "styles/*.mplstyle",
    "styles/color/*.mplstyle",
    "styles/misc/*.mplstyle",
    "styles/journals/*.mplstyle",
    "styles/size/*.mplstyle",
]


# (optional) exclude heavy/irrelevant content from the wheel
[tool.setuptools.exclude-package-data]
rwthplots = ["**/examples/**", "**/docs/**", "**/test/**"]
